version: '3'

services:
    sport_mysql:
        image: "mariadb:10.11.2"
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
    rabbitmq:
        image: rabbitmq:3-management
        ports: [ 5672, 15672 ]